
GET http://localhost:3000/events

###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
  "name": "event name",
  "description": "event description",
  "price": 100,
  "date": "2020-01-01T00:00:00.000Z"
}
###

@eventId = {{ createEvent.response.body.id }}

###
GET http://localhost:3000/events/{{eventId}}

###
PATCH http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
  "name": "event name 2",
  "description": "event description",
  "price": 100,
  "date": "2020-01-01T00:00:00.000Z"
}

###
DELETE http://localhost:3000/events/{{eventId}}


###SPOTS
GET http://localhost:3000/events/{{eventId}}/spots

###
# @name createSpot
POST http://localhost:3000/events/{{eventId}}/spots
Content-Type: application/json

{
  "name": "A3"
}
###

@spotId = {{ createSpot.response.body.id }}
@spotName = {{ createSpot.response.body.name }}

###
GET http://localhost:3000/events/{{eventId}}/spots/{{spotId}}

###
PATCH http://localhost:3000/events/{{eventId}}/spots/{{spotId}}
Content-Type: application/json

{
  "name": "A2",
  "description": "spot description",
  "price": 100
}

###
DELETE http://localhost:3000/events/{{eventId}}/spots/clxm8xo4v0001smim6kxg2n8h

###
POST http://localhost:3000/events/{{eventId}}/reserve
X-Api-Token: 123
Content-Type: application/json

{
  "spots": ["{{spotName}}"],
  "ticketKind": "full",
  "email": "teste@teste.com"
}



###Deve listar vazio 
GET http://localhost:3000/events 

### Deve criar um event # @name createEvent 
 
# @name createEvent
POST http://localhost:3000/events 
Content-Type: application/json 

{ 
  "name": "New Event", 
  "description": "This is a new event", 
  "date": "2017-01-01T00:00:00", 
  "price": 100 
  }
###
@eventId = {{ createEvent.response.body.id }} 
 
### Deve retornar 422 
POST http://localhost:3000/events 
Content-Type: application/json

{ } 

### Deve criar um spot 
# @name createSpot
POST http://localhost:3000/events/{{eventId}}/spots 
Content-Type: application/json 

{ "name": "A2" } 

###
@spotName = {{ createSpot.response.body.name }} 
### Deve retornar 422 
POST http://localhost:3000/events/{{eventId}}/spots 
Content-Type: application/json 

{ } 

### Deve gerar uma reserva. Se enviado novamente, precisa retornar um erro 
POST http://localhost:3000/events/{{eventId}}/reserve 
X-Api-Token: 1234
Content-Type: application/json 

{ 
  "spots": ["{{ spotName }}"], 
  "ticket_kind": "full", 
  "email": "test@test.com" 
}